name: Checar os links em .md

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-link:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3

    # Fix emergencial para corrigir erro fatal: unsafe repository na action
    - uses: labeneko/github-action-markdown-link-check@fixed-unsafe-repository
      with:
        check-modified-files-only: 'yes'
        base-branch: 'main'
